# generated by scripts/generate_formula.py, do not edit by hand
class Splat < Formula
  desc "Universal converter and model-backed toolkit for Gaussian splats and images"
  homepage "https://github.com/daanrongen/splat"
  url "https://github.com/daanrongen/splat/releases/download/v0.1.0/splat-0.1.0.tar.gz"
  sha256 "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
  license "MIT"

  depends_on arch: :arm64
  depends_on :macos
  depends_on "git" => :build
  depends_on "python@3.12"
  depends_on "uv"

  def install
    ENV["UV_PROJECT_ENVIRONMENT"] = libexec/"venv"
    system "uv", "sync", "--frozen", "--no-dev", "--no-editable",
           "--python", Formula["python@3.12"].opt_bin/"python3.12"
    bin.install_symlink libexec/"venv/bin/splat"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/splat --version")
  end
end
