# generated by scripts/generate_formula.py, do not edit by hand
class Splat < Formula
  desc "Universal converter and model-backed toolkit for Gaussian splats and images"
  homepage "https://github.com/daanrongen/splat"
  url "https://github.com/daanrongen/splat/releases/download/v0.1.2/splat-0.1.2-src.tar.gz"
  sha256 "8c27becb402bd6cd2e9b8ce60543c5743d99a4c936ff8e1e28c2b02f38fcbd75"
  license "MIT"

  depends_on arch: :arm64
  depends_on :macos
  depends_on "git" => :build
  depends_on "python@3.12"
  depends_on "uv"

  def install
    ENV["UV_PROJECT_ENVIRONMENT"] = libexec/"venv"
    system "uv", "sync", "--frozen", "--no-dev", "--no-editable",
           "--python", Formula["python@3.12"].opt_bin/"python3.12"
    bin.install_symlink libexec/"venv/bin/splat"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/splat --version")
  end
end
