# generated by scripts/generate_formula.py, do not edit by hand
class Splat < Formula
  desc "Universal converter and model-backed toolkit for Gaussian splats and images"
  homepage "https://github.com/daanrongen/splat"
  url "https://github.com/daanrongen/splat/releases/download/v0.1.3/splat-0.1.3-src.tar.gz"
  sha256 "f636311d7a38f0f795df99557e9fbab9f6e8f2e6a7d2680353cf6622cef0d72e"
  license "MIT"

  depends_on arch: :arm64
  depends_on :macos
  depends_on "git" => :build
  depends_on "python@3.12"
  depends_on "uv"

  def install
    ENV["UV_PROJECT_ENVIRONMENT"] = libexec/"venv"
    system "uv", "sync", "--frozen", "--no-dev", "--no-editable",
           "--python", Formula["python@3.12"].opt_bin/"python3.12"
    bin.install_symlink libexec/"venv/bin/splat"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/splat --version")
  end
end
